### ISSUE TITLE
Update readme examples

### ISSUE THREAD

**Issue by Spreeuw** [nizarmah/auto-minify#18]
The version constraints in the readme examples are a little dated or not ideal I would suggest to make these changes:
```yml
stefanzweifel/git-auto-commit-action@v3.0.0
```
to:
```yml
stefanzweifel/git-auto-commit-action@v4
```
and your own:
```yml
nizarmah/auto-minify@master
```
I would change to
```yml
nizarmah/auto-minify@v2
```
(I would consider `master` to be more like the bleeding edge for people who need quick access to an unreleased fix, but stable releases more suitable for most people)

**Comment by nizarmah** [comment]
@Spreeuw you're right! Thanks for that! Back when I wrote the README, I included `master` without any regard to the importance of having actions not unexpectedly "break". 

Regarding the `git-auto-commit-action` upgrade, sounds good as well 👍🏼 Would you prefer to open a pull request with those changes and have me review it? Or would you like me to create a pull request, while handling the review? Let me know 😃 

> I can also create a PR without your review, but a little bit of friction over PRs is beneficial for both parties involved 😉

**Comment by nizarmah** [comment]
Thanks for the review @Spreeuw and for the helpful suggestions 😃 I hope you have a nice day!
