### ISSUE TITLE
Mark action as failed on error in minification process 

### ISSUE THREAD

**Issue by C0pyR1ght** [nizarmah/auto-minify#3]
I think it would be helpful to set the action as failed if for example a `Parse error` occurs during minification process because the scoped files are not actually minified and therefore the goal not reached.

Several Times I had some minor typos within the files to me minified that lead to a `Parse error`. Therefore the file was obviously not commited to the repo but the action was always marked as `successfull` which is very missleading. You have to manually dive through the action logs to discover the failed minification process.

**Comment by nizarmah** [comment]
Hello @C0pyR1ght  ( :

You are totally right! I will get to work on that as soon as possible. Thank you for the issue and the recommendation :D

I'll keep track of this issue in my commits and pull requests so you can see the progress ( :

**Comment by nizarmah** [comment]
Alright, so here's a quick update. I implemented the code necessary. I just need to launch a Docker image and test it for myself. Once it passes the tests I want, I'll pull and update the action! ( :

**Comment by nizarmah** [comment]
Testing Log can be found in [Auto-Minify-Test/Issues#3](https://github.com/nizarmah/auto-minify-test/tree/issues%233).

![image](https://user-images.githubusercontent.com/5631091/79830972-392d3180-83af-11ea-8baa-b22eb054761b.png)

**Comment by nizarmah** [comment]
Alright, updated the action in the [marketplace](https://github.com/marketplace/actions/auto-minify).

Use the latest version, `v1.5` and it should work as you wish ( : 

Thanks a lot for the recommendation!

**Comment by nizarmah** [comment]
Kindly let me know if there is anything other way I can improve the Action :smile:
